import "dotenv/config";

export const ENV = {
  PORT: process.env.PORT,
  MONGO_URL: process.env.MONGO_URL,
  JWT_SECRET: process.env.SECRET_KEY,
  NODE_ENV: process.env.NODE_ENV,
  CLIENT_URL: process.env.CLIENT_URL,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  EMAIL_FROM: process.env.EMAIL_FROM,
  EMAIL_FROM_NAME: process.env.EMAIL_FROM_NAME,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  ARCJET_KEY: process.env.ARCJET_KEY,
  ARCJET_ENV: process.env.ARCJET_ENV,
  CLOUDENARY_SECRET:process.env.CLOUDENARY_SECRET,
  CLOUDENARY_API_KEY:process.env.CLOUDENARY_API_KEY,
  CLOUDENARY_NAME:process.env.CLOUDENARY_NAME,
  ARJECT_ENV:process.env.ARJECT_ENV,
  ARJECT_KEY:process.env.ARCJET_KEY
};